version: "3.9"
services:
  web:
    image: go-get-started:latest
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always 
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
