name: webapp-build-lint-test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: |
            make build

      - name: Get linter
        run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b $(go env GOPATH)/bin

      - name: Lint
        run: |
            make lint

      - name: Test & Coverage
        run: |
            make test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.out
